Algoritmo "contador-decrescente"
//  
//  



Var

   contador,numero,somatorio:inteiro

Inicio

      
      escreval("Contar ate quanto?")
      leia(numero)
      
      contador<-0
      
      enquanto (contador<=numero) faça
      
               escreval("Somatório:",contador)
               
               
               contador<-contador+contador
      
      fimenquanto



Fimalgoritmo